//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int ID { get; set; }
        public string Nazwa_albumu { get; set; }
        public string Nazwa_zespołu { get; set; }
        public int Rok_wydania { get; set; }
        public Nullable<System.TimeSpan> Czas { get; set; }
        public string Rodzaj { get; set; }
        public string Wytwórnia { get; set; }
        public byte[] Okładka { get; set; }
    }
}
