//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prawa
    {
        public string ID_praw { get; set; }
        public string Nazwa_praw { get; set; }
        public int Usuwanie { get; set; }
        public int Dodawanie { get; set; }
        public int Przegladanie { get; set; }
    }
}
