//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statystyki
    {
        public int Id_statystyki { get; set; }
        public int Id_utworu { get; set; }
        public Nullable<System.DateTime> Ostatnie_odtworzenie { get; set; }
        public Nullable<System.DateTime> Piersze_odtworzenie { get; set; }
        public int Ilosc_wysłuchań { get; set; }
        public string Login { get; set; }
    }
}
