//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        public string Login { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string E_mail { get; set; }
        public string Hasło { get; set; }
        public string Prawa_ { get; set; }
        public Nullable<System.DateTime> Data_urodzenia { get; set; }
    }
}
